### ISSUE TITLE
Input forms unvalidated

### ISSUE THREAD

**Issue by AlexeiDarmin** [theresama/SynergySpace#2]
I have been unable in finding a Regex to successfully check valid emails in HTML5.

Currently, emails bypass HTML5 checks and are caught by ruby. This is undesired since HTML5 forces this restraint while the form is being completed whereas for ruby to catch it, a call has to be made to various functions and the page is reloaded (substantially slower and more resource heavy than HTML5).

**Comment by theresama** [comment]
Alexei, if you want to do it on the front end as the user is filling in the form, you can use javascript.
http://emailregex.com/ there's a regex there you can use.

**Comment by AlexeiDarmin** [comment]
I just don't understand why we have "type=email" if it fails to validate email types correctly.

Thanks for the link, if we have the regex then we can do it in HTML5, don't even need JS :) I'll do it in a bit.
